include("${SOURCE_DIR}/tools/build/RuntimeBuildIdentity.cmake")

tetrisphere_bind_runtime_identity(first "project-material" "runtime-source-a:rt64-source-a")
tetrisphere_bind_runtime_identity(repeated "project-material" "runtime-source-a:rt64-source-a")
tetrisphere_bind_runtime_identity(changed "project-material" "runtime-source-a:rt64-source-b")
if(NOT first STREQUAL repeated)
    message(FATAL_ERROR "runtime-bound build identity is not deterministic")
endif()
if(first STREQUAL changed)
    message(FATAL_ERROR "build identity did not change with RT64 source identity")
endif()

set(receipt_lf "${CMAKE_CURRENT_BINARY_DIR}/identity-lf.json")
set(receipt_crlf "${CMAKE_CURRENT_BINARY_DIR}/identity-crlf.json")
set(receipt_json "{\"name\":\"rt64\",\"commit\":\"43373749dac9bbc1b653e6a02aed40a9e1783bed\",\"source_identity\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"lock_digest\":\"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\"}")
file(WRITE "${receipt_lf}" "${receipt_json}\n")
string(REPLACE "\n" "\r\n" receipt_json_crlf "${receipt_json}\n")
file(WRITE "${receipt_crlf}" "${receipt_json_crlf}")
tetrisphere_receipt_identity(identity_lf "${receipt_lf}")
tetrisphere_receipt_identity(identity_crlf "${receipt_crlf}")
if(NOT identity_lf STREQUAL identity_crlf)
    message(FATAL_ERROR "logical receipt identity depends on line endings")
endif()
